version: "3.8"
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    # set hostname to resolve this error
    # https://stackoverflow.com/a/38742537/6952495
    # https://docs.docker.com/compose/compose-file/#extra_hosts
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - "9092:9092"
    environment:
      # in prod need to change this if using multiple brokers
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # https://github.com/wurstmeister/kafka-docker#automatically-create-topics
      KAFKA_CREATE_TOPICS: "queue.podcast-analysis-tool.query-term,queue.podcast-analysis-tool.search-result-json,queue.podcast-analysis-tool.podcast,queue.podcast-analysis-tool.episode"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  extract-episodes-per-podcasts: 
    image: "ryanquey/java-workers"
    # TODO hopefully one day these volumes will mean we don't need to download all the dependencies into the container, particularly for development. 
    # In prod will just use the custom image. 
    # See instructions here: https://hub.docker.com/_/maven, .
    #volumes: 
    #- ${JAVA_WORKERS_DIR:-.}:/usr/src/podcast_analysis_tool
    # cmd to run on startup
    entrypoint: ["java", "-jar", "target/extract-episodes-per-podcasts-0.3.0.jar"]
    environment:
      KAFKA_URL: kafka:9092
      CASSANDRA_URL: seed_node
  run-search-per-term: 
    image: "ryanquey/java-workers"
    # cmd to run on startup
    entrypoint: ["java", "-jar", "target/run-search-per-term-0.3.0.jar"]
    environment:
      KAFKA_URL: kafka:9092
      CASSANDRA_URL: seed_node
  extract-podcasts-per-search:
    image: "ryanquey/java-workers"
    # cmd to run on startup
    entrypoint: ["java", "-jar", "target/extract-podcasts-per-search-0.3.0.jar"]
    environment:
      KAFKA_URL: kafka:9092
      CASSANDRA_URL: seed_node
